version: 2

models:
  - name: silver_salesinfo
    description: "A table containing sales data at the silver level."
    columns:
        - name: category
          description: "The category of the returned item."
          data_type: string 
        - name: gender
          description: "Gender of the customer."
          data_type: string
        - name: total_sales
          description: "Total sales amount by category and gender."
          data_type: double
  - name: silver_returnsinfo
    description: "A table containing returns data at the silver level."
    columns:
        - name: category
          description: "The category of the returned item."
          data_type: string
        - name: product_sk  
          description: "surrogate key for product table."
          data_type: bigint
        - name: total_refunds 
          description: "Total refunds amount by category and gender."  
          data_type: double
  - name: silver_storesales
    description: "A table containing store sales data at the silver level."
    columns:
      - name: store_sk
        description: "surrogate key for store table."
        data_type: bigint
      - name: store_name
        description: "The name of the store."
        data_type: string
      - name: city
        description: "The city where the store is located."      
        data_type: string
      - name: state_province  
        description: "The state or province where the store is located."
        data_type: string
      - name: country 
        description: "The country where the store is located."
        data_type: string
