
sources:
  - name: source
    database: training2 
    schema: source
    tables:
      - name: fact_returns
        description: Returns fact table
      - name: dim_date
        description: Date dimension table
      - name: dim_store
        description: Store dimension table
      - name: dim_product
        description: Product dimension table
      - name: dim_customer
        description: Customer dimension table
      - name: fact_sales
        description: Sales fact table
      - name: items
        description: Items table