version: 2

models:
  - name: bronze_customers
    description: "A table containing customer data at the bronze level."
    columns:
      - name: customer_sk
        description: "surrogate key for customer table."
        data_type: string
      - name: customer_code
        description: "The unique identifier for each customer."
        data_type: string
      - name: first_name
        description: "The first name of the customer."
        data_type: string
      - name: last_name
        description: "The last name of the customer."
        data_type: string
      - name: email
        description: "The email address of the customer."
        data_type: string 
      - name: gender
        description: "The gender of the customer."  
        data_type: string
      - name: phone
        description: "The phone number of the customer."
        data_type: string
      - name: loyalty_tier
        description: "The loyalty tier of the customer."
        data_type: string
      - name: signup_date
        description: "The date the customer signed up."
        data_type: date
